export const siteConfig = {
  title: 'Sheep 的项目导航',
  subtitle: '把分散的个人项目收拢到一个落地页',
  description:
    '把平时折腾的个人项目和实验 Demo 收拢到一个地方，方便自己和朋友随时找到入口。',
  links: {
    github: 'https://github.com/wingsheep', // 可以改成你的 GitHub 主页
    // blog: 'https://your-blog.com',
  },
  // 默认主题：'light' | 'dark' | 'system'
  defaultTheme: 'system',
}

// 分组 / 分类配置：
// 按类别组织项目，不需要维护过多层级，保持结构清晰。
// 只需要维护这里的分组和项目列表，导航页会自动渲染更新。
export const projectGroups = [
  {
    id: 'featured',
    name: '📌 精选 / 置顶',
    description: '近期最活跃、最值得展示的核心项目',
    projects: [
      {
        id: 'pj-cli',
        name: 'pj-cli',
        description: '一款终端项目快速跳转工具。通过为项目配置别名，支持使用别名、拼音（全拼/首字母缩写）或路径关键词极速 cd 到目标目录。',
        techStack: ['Node.js', 'TypeScript', 'CLI'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/pj-cli',
        demoUrl: '',
        status: 'online',
        highlight: true,
      },
      {
        id: 'ehr-app',
        name: 'Ehr App',
        description: '基于 Tauri 2 + Vue 3 的桌面应用，自动登录 italent.cn EHR 系统、抓取考勤打卡时间，并在系统托盘实时显示下班倒计时。',
        techStack: ['Tauri', 'Vue 3'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/ehr-tauri',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
      {
        id: 'mcp-use-demo',
        name: 'Mcp Use Demo',
        description: 'MCP Use + DeepSeek 的完整链路 Demo，包含 MCP Server/UI resources、MCP Client/Agent、API 层与 Nuxt Web 前端。',
        techStack: ['MCP Use', 'langchain/openai', 'Zod', 'Typescript', 'Nuxt 4'],
        repoUrl: 'https://github.com/wingsheep/mcp-use-demo',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
    ],
  },
  {
    id: 'ai-mcp',
    name: '🤖 AI 与大模型',
    description: 'MCP 服务端实现、AI Agent 工作流以及与 AI 结对编程的产物。',
    projects: [
      {
        id: 'fuxi-mcp',
        name: '伏羲平台 MCP',
        description: '封装海管家/伏羲平台的登录、项目查询、发布、消息通知及常用运维接口，同时支持 MCP 服务端 和 CLI 命令行两种使用方式，并提供 AI Agent 技能。',
        techStack: ['Mcp', 'Zod', 'Typescript'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/hgj-fuxi-mcp',
        demoUrl: '',
        status: 'wip',
        highlight: false,
      },
      {
        id: 'code-members',
        name: '研发委员会',
        description: 'AI Vibe Coding 产物。帮助有意参与的同事快速了解研发委员会的制度与开放项目，便于参考、对齐和持续完善。',
        techStack: ['Vue 3', 'Vite', 'Mermaid'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/codemembers',
        demoUrl: 'https://codemembers.happyfly.top/',
        status: 'online',
        highlight: false,
      },
      {
        id: 'code-poem-1024',
        name: '1024 程序员节｜代码猜诗词',
        description: 'AI Vibe Coding 产物。公司 1024 活动，把程序员的浪漫写进代码，用代码来猜诗词。',
        techStack: ['HTML'],
        repoUrl: 'https://github.com/wingsheep/code-poem-1024',
        demoUrl: 'https://codepoem.happyfly.top/',
        status: 'online',
        highlight: false,
      },
    ],
  },
  {
    id: 'extensions',
    name: '🔌 效率插件',
    description: '提升编码与工作体验的 VS Code、Raycast 及浏览器扩展。',
    projects: [
      {
        id: 'cosbrowser-vscode',
        name: 'Cosbrowser Autocomplete',
        description: '一个 VS Code 插件，编写代码时智能补全腾讯云 COS 里的文件路径，支持 CDN 域名替换和图片预览。',
        techStack: ['VS Code', 'TypeScript'],
        repoUrl: 'https://github.com/wingsheep/cosbrowser-autocomplete',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
      {
        id: 'cosbrowser-raycast',
        name: 'Cosbrowser (Raycast)',
        description: '一个 Raycast 插件，用于快捷管理和打开 Cosbrowser 相关入口。',
        techStack: ['React', 'TypeScript'],
        repoUrl: 'https://github.com/wingsheep/cosbrowser',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
      {
        id: 'hgj-ops-raycast',
        name: 'Hgj Ops Raycast',
        description: '一个整合了海管家国内外伏羲平台常用入口的 Raycast 扩展。',
        techStack: ['React', 'TypeScript'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/hgj-ops-raycast',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
      {
        id: 'codevar-raycast',
        name: 'CodeVar',
        description: '一个基于有道翻译 API 的 Raycast 扩展，用来辅助生成代码中的变量命名。',
        techStack: ['React', 'TypeScript'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/code-var',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
      {
        id: 'tampermonkey-script',
        name: 'Tampermonkey Script',
        description: '用油猴脚本把工作中一些重复又烦人的小步骤自动化，省心省力。',
        techStack: ['Javascript'],
        repoUrl: 'https://github.com/wingsheep/tampermonkey-script',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
    ],
  },
  {
    id: 'desktop-cli',
    name: '💻 桌面与命令行',
    description: '独立运行的桌面端程序与终端 CLI 工具。',
    projects: [
      {
        id: 'sync-locale-tauri',
        name: 'Sync GitLab Locale (Tauri v2)',
        description: '使用 Tauri v2 重构的海外舱单语言包同步跨平台桌面应用。',
        techStack: ['Tauri', 'Vue'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/sync-locale-app_by_tauri-v2',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
      {
        id: 'sync-locale-electron',
        name: 'Sync Locale App',
        description: '基于 Electron 的海外舱单语言包同步应用，方便开发和测试快速同步语言包。',
        techStack: ['Electron', 'Vue'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/sync-locale-app',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
    ],
  },
  {
    id: 'web-experiments',
    name: '🕸️ Web 与实验',
    description: 'Web 应用 Demo、技术验证与一些玩具项目。',
    projects: [
      {
        id: 'ui-test-demo',
        name: 'UI 自动化测试 Demo',
        description: '可视化录制 + 后台执行的 UI 自动化平台 MVP。',
        techStack: ['Playwright', 'Node.js', 'Docker', 'Nuxt 4'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/ui-test-demo',
        demoUrl: '',
        status: 'online',
        highlight: false,
      },
    ],
  },
  {
    id: 'talks',
    name: '🎤 演讲与分享',
    description: '技术分享相关的内容统一入口，Slides 与 Demo 代码集中存放在这里。',
    projects: [
      {
        id: 'talks-nav',
        name: '演讲导航页',
        description: '把过往演讲集中在一个导航页里，方便自己和同事随时回看。',
        techStack: ['Vue 3', 'Vite', 'TypeScript'],
        repoUrl: 'https://github.com/wingsheep/talks',
        demoUrl: 'https://www.talks.happyfly.top/',
        status: 'online',
        highlight: false,
      },
      {
        id: 'talks-vue3',
        name: 'Vue3 优雅的开发项目',
        description: '和大家分享如何用 Vue 3 + Vite 组装一个体验相对优雅、可维护性不错的前端项目。',
        techStack: ['Vue 3', 'Vite', 'TypeScript'],
        repoUrl: 'https://github.com/wingsheep/talks/tree/master/2022-07-10',
        demoUrl: 'https://www.talks.happyfly.top/2022/vue3-ecosystem/1',
        status: 'online',
        highlight: false,
      },
    ],
  },
  {
    id: 'archived',
    name: '📦 归档',
    description: '不再积极维护，但作为历史参考保留的项目。',
    projects: [
      {
        id: 'hgj-cicd',
        name: '海管家 CI CD',
        description: '海管家项目部署相关脚本导航目录。',
        techStack: ['Node.js'],
        repoUrl: 'http://git.hgj.net/taoxiang.tao/hgj-cicd',
        demoUrl: '',
        status: 'archived',
        highlight: false,
      },
      {
        id: 'certbot-ops',
        name: 'Certbot 脚本',
        description: '使用 Certbot 自动续期证书，并把最新证书自动上传到七牛云。',
        techStack: ['Shell', 'Python'],
        repoUrl: 'https://github.com/wingsheep/ops',
        demoUrl: '',
        status: 'archived',
        highlight: false,
      },
    ],
  },
]
